name = "datebook"
version = "1.1.0"
description = "Extensions to gleam/time to work with weekdays, months, and dates"
licences = ["MIT"]
repository = { type = "github", user = "steinuil", repo = "datebook" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
